version: "3"
services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - "torders-api:api"
      - "torders-worker-monitor:monitor"
      - "torders-client:client"
  torders-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    volumes:
     - ./results:/results
     - ./public:/public
    depends_on:
      - redis
  torders-worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
     - ./results:/results
     - ./public:/public
  torders-worker-monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  torders-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
  redis:
    image: redis