version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
  torders-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    volumes:
     - ./results:/results
     - ./public:/public
    depends_on:
      - redis
      - nginx-proxy
    ports:
      - "5001:80"
    environment:
      VIRTUAL_HOST: torders.stanford.edu/api
      VIRTUAL_PORT: 5001
  torders-worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
      - nginx-proxy
    volumes:
     - ./results:/results
     - ./public:/public
  torders-worker-monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
      - nginx-proxy
    ports:
      - "5555:80"
    environment:
      VIRTUAL_HOST: torders.stanford.edu/monitor
      VIRTUAL_PORT: 5555
  torders-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      VIRTUAL_HOST: torders.stanford.edu
      VIRTUAL_PORT: 8080
    depends_on:
      - nginx-proxy
  redis:
    image: redis