version: "3"
services:
  torders-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    volumes:
     - ./results:/results
     - ./public:/public
    ports:
     - "5001:5001"
    depends_on:
      - redis
  torders-worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
     - ./results:/results
     - ./public:/public
  torders-worker-monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    ports:
     - "5555:5555"
    depends_on:
      - redis
  torders-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
     - "80:80"
  redis:
    image: redis