version: "3"
services:
  torders-web:
    build: ./app
    image: torders
    ports:
      - 2014:2014
    command: ["web", "--reload"]
    volumes:
      - ./uploads:/uploads
      - ./results:/results
      - ./app:/app
    depends_on:
      - redis
  torders-worker:
    build: ./app
    image: torders
    command: ["worker", "--reload"]
  redis:
    image: redis:3-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
